# Generated by Django 5.2.3 on 2025-07-09 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneResponse',
            fields=[
                ('scene_response_id', models.AutoField(primary_key=True, serialize=False)),
                ('dispatch_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('preliminary_assessment', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('case_id', models.ForeignKey(db_column='case_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
            options={
                'db_table': 'scene_responses',
            },
        ),
        migrations.CreateModel(
            name='ScenePreservation',
            fields=[
                ('preservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('officer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('protection_methods', models.TextField(blank=True, null=True)),
                ('area_covered', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachment_url', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('scene_response_id', models.ForeignKey(db_column='scene_response_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='scene.sceneresponse')),
            ],
            options={
                'db_table': 'scene_preservations',
            },
        ),
        migrations.CreateModel(
            name='SceneDescription',
            fields=[
                ('description_id', models.AutoField(primary_key=True, serialize=False)),
                ('detail_description', models.TextField(blank=True, null=True)),
                ('important_object_locations', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('scene_response_id', models.ForeignKey(db_column='scene_response_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='scene.sceneresponse')),
            ],
            options={
                'db_table': 'scene_descriptions',
            },
        ),
        migrations.CreateModel(
            name='MedicalSupport',
            fields=[
                ('support_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_id', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_support', models.CharField(blank=True, max_length=100, null=True)),
                ('personnel_assigned', models.TextField(blank=True, null=True)),
                ('location_assigned', models.TextField(blank=True, null=True)),
                ('scene_sketch_url', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('scene_response_id', models.ForeignKey(db_column='scene_response_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='scene.sceneresponse')),
            ],
            options={
                'db_table': 'medical_supports',
            },
        ),
        migrations.CreateModel(
            name='SceneStatement',
            fields=[
                ('statement_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(blank=True, max_length=100, null=True)),
                ('statement_date', models.DateField(blank=True, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('file_url', models.TextField(blank=True, null=True)),
                ('statement_content', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('scene_response_id', models.ForeignKey(db_column='scene_response_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='scene.sceneresponse')),
            ],
            options={
                'db_table': 'scene_statements',
            },
        ),
    ]
