# Generated by Django 5.2.3 on 2025-07-09 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseArrest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'case_arrests',
            },
        ),
        migrations.CreateModel(
            name='Arrest',
            fields=[
                ('arrest_id', models.AutoField(primary_key=True, serialize=False)),
                ('suspect_miranda_signature', models.TextField(blank=True, null=True)),
                ('arrest_start_time', models.DateTimeField(blank=True, null=True)),
                ('arrest_end_time', models.DateTimeField(blank=True, null=True)),
                ('holiday_conflict', models.BooleanField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('holiday_id', models.ForeignKey(db_column='holiday_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderation.holiday')),
                ('officer_id', models.ForeignKey(db_column='officer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'arrests',
            },
        ),
    ]
