# Generated by Django 5.2.3 on 2025-07-09 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arrests', '0001_initial'),
        ('cases', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrest',
            name='suspect_id',
            field=models.ForeignKey(db_column='suspect_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.suspect'),
        ),
        migrations.AddField(
            model_name='casearrest',
            name='arrest_id',
            field=models.ForeignKey(db_column='arrest_id', on_delete=django.db.models.deletion.CASCADE, to='arrests.arrest'),
        ),
        migrations.AddField(
            model_name='casearrest',
            name='case_id',
            field=models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, to='cases.case'),
        ),
        migrations.AlterUniqueTogether(
            name='casearrest',
            unique_together={('arrest_id', 'case_id')},
        ),
    ]
