# Generated by Django 5.2.3 on 2025-07-09 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cases', '0001_initial'),
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureSurvey',
            fields=[
                ('measure_survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'measure_surveys',
            },
        ),
        migrations.CreateModel(
            name='Warrant',
            fields=[
                ('warrant_id', models.AutoField(primary_key=True, serialize=False)),
                ('warrant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attached_file', models.TextField(blank=True, null=True)),
                ('time_pulish', models.DateTimeField(blank=True, null=True)),
                ('warrant_status', models.CharField(blank=True, max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('case_id', models.ForeignKey(db_column='case_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('officer_username', models.ForeignKey(db_column='officer_username', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
            options={
                'db_table': 'warrants',
            },
        ),
        migrations.CreateModel(
            name='WarrantResult',
            fields=[
                ('warrant_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('police_response', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('time_active', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('warrant_id', models.ForeignKey(db_column='warrant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='warrants.warrant')),
            ],
            options={
                'db_table': 'warrant_results',
            },
        ),
        migrations.CreateModel(
            name='WarrantEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('evidence_id', models.ForeignKey(db_column='evidence_id', on_delete=django.db.models.deletion.CASCADE, to='evidence.evidence')),
                ('warrant_id', models.ForeignKey(db_column='warrant_id', on_delete=django.db.models.deletion.CASCADE, to='warrants.warrant')),
            ],
            options={
                'db_table': 'warrant_evidences',
                'unique_together': {('warrant_id', 'evidence_id')},
            },
        ),
    ]
