# Generated by Django 5.2.3 on 2025-07-09 16:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('type_case', models.CharField(blank=True, max_length=100, null=True)),
                ('severity', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('case_target', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cases',
            },
        ),
        migrations.CreateModel(
            name='Indictment',
            fields=[
                ('indictments_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'indictments',
            },
        ),
        migrations.CreateModel(
            name='Inmate',
            fields=[
                ('inmate_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_facility', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_release', models.DateField(blank=True, null=True)),
                ('health_status', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'inmates',
            },
        ),
        migrations.CreateModel(
            name='Prosecution',
            fields=[
                ('prosecution_id', models.AutoField(primary_key=True, serialize=False)),
                ('decision', models.TextField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('reasion', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'prosecutions',
            },
        ),
        migrations.CreateModel(
            name='ProsecutionSuspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'prosecution_suspects',
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('sentence_id', models.AutoField(primary_key=True, serialize=False)),
                ('sentence_type', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('sentencing_date', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sentences',
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('timeline_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('attached_file', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('activity', models.TextField(blank=True, null=True)),
                ('holiday_conflict', models.BooleanField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'timelines',
            },
        ),
        migrations.CreateModel(
            name='UserCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.BooleanField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_cases',
            },
        ),
        migrations.CreateModel(
            name='CaseResult',
            fields=[
                ('case_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_time', models.DateTimeField(blank=True, null=True)),
                ('report_analyst', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('identify_motive', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('case_id', models.ForeignKey(db_column='case_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
            options={
                'db_table': 'case_results',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('holiday_conflict', models.BooleanField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('case_id', models.ForeignKey(db_column='case_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('holiday_id', models.ForeignKey(db_column='holiday_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderation.holiday')),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
