# Generated by Django 5.2.3 on 2025-07-09 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cases', '0001_initial'),
        ('moderation', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='suspect_id',
            field=models.ForeignKey(db_column='suspect_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.suspect'),
        ),
        migrations.AddField(
            model_name='prosecution',
            name='case_id',
            field=models.ForeignKey(db_column='case_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.case'),
        ),
        migrations.AddField(
            model_name='prosecution',
            name='prosecutor_id',
            field=models.ForeignKey(db_column='prosecutor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user'),
        ),
        migrations.AddField(
            model_name='indictment',
            name='prosecution_id',
            field=models.ForeignKey(db_column='prosecution_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.prosecution'),
        ),
        migrations.AddField(
            model_name='prosecutionsuspect',
            name='prosecution_id',
            field=models.ForeignKey(db_column='prosecution_id', on_delete=django.db.models.deletion.CASCADE, to='cases.prosecution'),
        ),
        migrations.AddField(
            model_name='prosecutionsuspect',
            name='suspect_id',
            field=models.ForeignKey(db_column='suspect_id', on_delete=django.db.models.deletion.CASCADE, to='reports.suspect'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='case_id',
            field=models.ForeignKey(db_column='case_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.case'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='case_result_id',
            field=models.ForeignKey(db_column='case_result_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.caseresult'),
        ),
        migrations.AddField(
            model_name='inmate',
            name='sentence_id',
            field=models.ForeignKey(db_column='sentence_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.sentence'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='case_result_id',
            field=models.ForeignKey(db_column='case_result_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.caseresult'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='holiday_id',
            field=models.ForeignKey(db_column='holiday_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderation.holiday'),
        ),
        migrations.AddField(
            model_name='usercase',
            name='case_id',
            field=models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, to='cases.case'),
        ),
        migrations.AddField(
            model_name='usercase',
            name='officer_id',
            field=models.ForeignKey(db_column='officer_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.AlterUniqueTogether(
            name='prosecutionsuspect',
            unique_together={('prosecution_id', 'suspect_id')},
        ),
        migrations.AlterUniqueTogether(
            name='usercase',
            unique_together={('case_id', 'officer_id')},
        ),
    ]
