# Generated by Django 5.2.3 on 2025-07-09 16:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cases', '0001_initial'),
        ('evidence', '0001_initial'),
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInvest',
            fields=[
                ('evidence_id', models.ForeignKey(db_column='evidence_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='evidence.evidence')),
                ('summary', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'financial_invests',
            },
        ),
        migrations.CreateModel(
            name='InvestigationPlan',
            fields=[
                ('investigation_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('create_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('plan_content', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('holiday_conflict', models.BooleanField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('accepted_officer_username', models.ForeignKey(db_column='accepted_officer_username', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_plans', to='accounts.user')),
                ('case_id', models.ForeignKey(db_column='case_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('created_officer_username', models.ForeignKey(db_column='created_officer_username', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to='accounts.user')),
                ('holiday_id', models.ForeignKey(db_column='holiday_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderation.holiday')),
            ],
            options={
                'db_table': 'investigation_plans',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('interview_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.TextField(blank=True, null=True)),
                ('attached_file', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('holiday_conflict', models.BooleanField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('holiday_id', models.ForeignKey(db_column='holiday_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderation.holiday')),
                ('interviewer_id', models.ForeignKey(db_column='interviewer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('investigation_plan_id', models.ForeignKey(db_column='investigation_plan_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='investigations.investigationplan')),
            ],
            options={
                'db_table': 'interviews',
            },
        ),
        migrations.CreateModel(
            name='ForensicInvestResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_name', models.CharField(blank=True, max_length=100, null=True)),
                ('report', models.TextField(blank=True, null=True)),
                ('result_summary', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('evidence_id', models.ForeignKey(db_column='evidence_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='evidence.evidence')),
                ('investigation_plan_id', models.ForeignKey(db_column='investigation_plan_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='investigations.investigationplan')),
            ],
            options={
                'db_table': 'forensic_invest_results',
            },
        ),
        migrations.CreateModel(
            name='DigitalInvestResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_type', models.CharField(blank=True, max_length=100, null=True)),
                ('analyst_tool', models.CharField(blank=True, max_length=100, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('evidence_id', models.ForeignKey(db_column='evidence_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='evidence.evidence')),
                ('investigation_plan_id', models.ForeignKey(db_column='investigation_plan_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='investigations.investigationplan')),
            ],
            options={
                'db_table': 'digital_invest_results',
            },
        ),
        migrations.CreateModel(
            name='PhysicalInvestResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True, null=True)),
                ('attached_file', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('evidence_id', models.ForeignKey(db_column='evidence_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='evidence.evidence')),
                ('investigation_plan_id', models.ForeignKey(db_column='investigation_plan_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='investigations.investigationplan')),
            ],
            options={
                'db_table': 'physical_invest_results',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('reliability', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('interview_id', models.ForeignKey(db_column='interview_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='investigations.interview')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('victim_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('injurie', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('case_id', models.ForeignKey(db_column='case_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
            options={
                'db_table': 'victims',
            },
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('witness_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('statement', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('case_id', models.ForeignKey(db_column='case_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
            options={
                'db_table': 'witnesses',
            },
        ),
        migrations.CreateModel(
            name='VictimInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('interview_id', models.ForeignKey(db_column='interview_id', on_delete=django.db.models.deletion.CASCADE, to='investigations.interview')),
                ('victim_id', models.ForeignKey(db_column='victim_id', on_delete=django.db.models.deletion.CASCADE, to='investigations.victim')),
            ],
            options={
                'db_table': 'victim_interviews',
                'unique_together': {('victim_id', 'interview_id')},
            },
        ),
        migrations.CreateModel(
            name='WitnessInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('interview_id', models.ForeignKey(db_column='interview_id', on_delete=django.db.models.deletion.CASCADE, to='investigations.interview')),
                ('witness_id', models.ForeignKey(db_column='witness_id', on_delete=django.db.models.deletion.CASCADE, to='investigations.witness')),
            ],
            options={
                'db_table': 'witness_interviews',
                'unique_together': {('witness_id', 'interview_id')},
            },
        ),
    ]
