# Generated by Django 5.2.3 on 2025-07-09 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cases', '0001_initial'),
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_report', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('case_location', models.TextField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('reporter_fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('reporter_email', models.CharField(blank=True, max_length=100, null=True)),
                ('reporter_phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('case_id', models.ForeignKey(db_column='case_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('officer_approve_username', models.ForeignKey(db_column='officer_approve_username', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('suspect_id', models.AutoField(primary_key=True, serialize=False)),
                ('suspect_role', models.CharField(blank=True, max_length=50, null=True)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('national', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('identification', models.CharField(blank=True, max_length=50, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('catch_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('mugshot_url', models.TextField(blank=True, null=True)),
                ('fingerprints_hash', models.TextField(blank=True, null=True)),
                ('health_status', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('case_id', models.ForeignKey(db_column='case_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
            options={
                'db_table': 'suspects',
            },
        ),
        migrations.CreateModel(
            name='ReportVictim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('report_id', models.ForeignKey(db_column='report_id', on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
                ('victim_id', models.ForeignKey(db_column='victim_id', on_delete=django.db.models.deletion.CASCADE, to='investigations.victim')),
            ],
            options={
                'db_table': 'report_victims',
                'unique_together': {('report_id', 'victim_id')},
            },
        ),
        migrations.CreateModel(
            name='ReportWitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('report_id', models.ForeignKey(db_column='report_id', on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
                ('witness_id', models.ForeignKey(db_column='witness_id', on_delete=django.db.models.deletion.CASCADE, to='investigations.witness')),
            ],
            options={
                'db_table': 'report_witnesses',
                'unique_together': {('report_id', 'witness_id')},
            },
        ),
        migrations.CreateModel(
            name='ReportSuspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('report_id', models.ForeignKey(db_column='report_id', on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
                ('suspect_id', models.ForeignKey(db_column='suspect_id', on_delete=django.db.models.deletion.CASCADE, to='reports.suspect')),
            ],
            options={
                'db_table': 'report_suspects',
                'unique_together': {('report_id', 'suspect_id')},
            },
        ),
    ]
