# Generated by Django 5.2.3 on 2025-07-09 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='report_id',
            field=models.ForeignKey(db_column='report_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.report'),
        ),
    ]
