# Generated by Django 5.2.3 on 2025-07-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_suspect_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='severity',
            field=models.CharField(blank=True, choices=[('URGENT', 'Urgent'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=50, null=True),
        ),
    ]
