# Generated by Django 5.2.3 on 2025-07-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='severity',
            field=models.CharField(blank=True, choices=[('URGENT', 'Urgent'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=50, null=True),
        ),
    ]
