# Generated by Django 5.2.3 on 2025-07-09 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('holiday_id', models.AutoField(primary_key=True, serialize=False)),
                ('holiday_name', models.CharField(blank=True, max_length=255, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('week_of_month', models.IntegerField(blank=True, null=True)),
                ('weekday_name', models.CharField(blank=True, max_length=20, null=True)),
                ('fixed_date', models.DateField(blank=True, null=True)),
                ('is_federal', models.BooleanField(blank=True, null=True)),
                ('is_traditional', models.BooleanField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'holidays',
            },
        ),
        migrations.CreateModel(
            name='HolidayType',
            fields=[
                ('holiday_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'holiday_types',
            },
        ),
        migrations.CreateModel(
            name='HolidayObservance',
            fields=[
                ('observance_id', models.AutoField(primary_key=True, serialize=False)),
                ('applies_to', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('holiday_id', models.ForeignKey(db_column='holiday_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='moderation.holiday')),
            ],
            options={
                'db_table': 'holiday_observances',
            },
        ),
        migrations.AddField(
            model_name='holiday',
            name='holiday_type_id',
            field=models.ForeignKey(db_column='holiday_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='moderation.holidaytype'),
        ),
        migrations.CreateModel(
            name='StateHoliday',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('holiday_id', models.ForeignKey(db_column='holiday_id', on_delete=django.db.models.deletion.CASCADE, to='moderation.holiday')),
            ],
            options={
                'db_table': 'state_holidays',
                'unique_together': {('state_id', 'holiday_id')},
            },
        ),
    ]
