# Generated by Django 5.2.3 on 2025-07-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stateholiday',
            old_name='holiday_id',
            new_name='holiday',
        ),
        migrations.AlterUniqueTogether(
            name='stateholiday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stateholiday',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stateholiday',
            name='state_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='stateholiday',
            unique_together={('state_id', 'holiday')},
        ),
        migrations.AddIndex(
            model_name='stateholiday',
            index=models.Index(fields=['holiday'], name='holiday_id'),
        ),
    ]
