# Generated by Django 5.2.3 on 2025-07-09 16:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordInfo',
            fields=[
                ('record_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('date_collected', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'record_infos',
            },
        ),
        migrations.CreateModel(
            name='SuspectEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'suspect_evidences',
            },
        ),
        migrations.CreateModel(
            name='CaseEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('case_id', models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
            options={
                'db_table': 'case_evidences',
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('evidence_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_collected', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('detailed_description', models.TextField(blank=True, null=True)),
                ('initial_condition', models.TextField(blank=True, null=True)),
                ('preservation_measures', models.TextField(blank=True, null=True)),
                ('location_at_scene', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('attached_file', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('case_id', models.ForeignKey(db_column='case_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('collector_username', models.ForeignKey(db_column='collector_username', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
            options={
                'db_table': 'evidences',
            },
        ),
    ]
