# Generated by Django 5.2.3 on 2025-07-09 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidence', '0001_initial'),
        ('reports', '0001_initial'),
        ('warrants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='measure_survey_id',
            field=models.ForeignKey(db_column='measure_survey_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='warrants.measuresurvey'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='report_id',
            field=models.ForeignKey(db_column='report_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.report'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='warrant_result_id',
            field=models.ForeignKey(db_column='warrant_result_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='warrants.warrantresult'),
        ),
        migrations.AddField(
            model_name='caseevidence',
            name='evidence_id',
            field=models.ForeignKey(db_column='evidence_id', on_delete=django.db.models.deletion.CASCADE, to='evidence.evidence'),
        ),
        migrations.AddField(
            model_name='recordinfo',
            name='evidence_id',
            field=models.ForeignKey(db_column='evidence_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='evidence.evidence'),
        ),
        migrations.AddField(
            model_name='suspectevidence',
            name='evidence_id',
            field=models.ForeignKey(db_column='evidence_id', on_delete=django.db.models.deletion.CASCADE, to='evidence.evidence'),
        ),
        migrations.AddField(
            model_name='suspectevidence',
            name='suspect_id',
            field=models.ForeignKey(db_column='suspect_id', on_delete=django.db.models.deletion.CASCADE, to='reports.suspect'),
        ),
        migrations.AlterUniqueTogether(
            name='caseevidence',
            unique_together={('case_id', 'evidence_id')},
        ),
        migrations.AlterUniqueTogether(
            name='suspectevidence',
            unique_together={('suspect_id', 'evidence_id')},
        ),
    ]
