# Generated by Django 5.2.3 on 2025-07-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='evidence_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
